lti_app/urls.py
# -*- coding: utf-8 -*-
#
#  urls.py
#
#  Authors:
#       - Coumes Quentin <coumes.quentin@gmail.com>
#
from django.conf import settings
from django.urls import path

from lti_app import views
from lti_app.tests import views as test_views


app_name = "lti"

urlpatterns = [
    path('lti/C<int:wims_pk>/', views.wims_class, name="wims_class"),
    path('lti/C<int:wims_pk>/S<int:sheet_pk>/', views.wims_sheet, name="wims_sheet"),
    path('lti/C<int:wims_pk>/E<int:exam_pk>/', views.wims_exam, name="wims_exam"),
    path('', views.lms, name="lms"),
    path('<int:lms_pk>/', views.wims, name="wims"),
    path('<int:lms_pk>/<int:wims_pk>/', views.classes, name="classes"),
    path('<int:lms_pk>/<int:wims_pk>/<int:wclass_pk>/', views.activities, name="sheets"),
]

if settings.TESTING:  # pragma: no cover
    urlpatterns += [
        path('test/xml_ok/', test_views.xml_ok, name="test_xml_ok"),
        path('test/xml_error/', test_views.xml_error_response, name="test_xml_error"),
        path('test/xml_badly_formatted/', test_views.xml_badly_formatted,
             name="xml_badly_formatted"),
    ]

wimsLTI/urls.py
# -*- coding: utf-8 -*-
#
#  urls.py
#
#  Authors:
#       - Coumes Quentin <coumes.quentin@gmail.com>


from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lti_app.urls', namespace='lti')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
]

lti_app/views.py
# -*- coding: utf-8 -*-
#
#  views.py
#
#  Authors:
#       - Coumes Quentin <coumes.quentin@gmail.com>
#

import logging

import requests
import wimsapi
from django.conf import settings
from django.contrib import messages
from django.http import (Http404, HttpRequest, HttpResponse, HttpResponseBadRequest,
                         HttpResponseForbidden, HttpResponseNotAllowed, HttpResponseNotFound)
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.http import require_GET

from lti_app.enums import Role
from lti_app.exceptions import BadRequestException
from lti_app.models import GradeLinkExam, GradeLinkSheet, LMS, WIMS, WimsClass
from lti_app.utils import (MODE, check_custom_parameters, check_parameters, get_exam,
                           get_or_create_class, get_or_create_user, get_sheet, is_teacher,
                           is_valid_request, parse_parameters)


logger = logging.getLogger(__name__)

GET_ERROR_MSG = """405 Method Not Allowed: 'GET'<br><br>
This is usually caused by one of the following reason:
<ul>
    <li>Missing trailing slash '/' at the end of the URL
        (eg: "%s" instead of "%s").</li>
    <li>Used this URL outside of an LTI activity.</li>
</ul>
"""



def wims_class(request: HttpRequest, wims_pk: int) -> HttpResponse:
    """Redirect the client to the WIMS server corresponding to <pk>.

    Will retrieve/create the right WIMS' class/user according to informations in request.POST.

    Raises:
        - Http404 if no LMS corresponding to request.POST["tool_consumer_instance_guid"]
            has been found in the database.
        - PermissionDenied if the class corresponding to request.POST['context_id'] does not exists
            and roles in request.POST['context_id'] are not one of
            settings.ROLES_ALLOWED_CREATE_WIMS_CLASS.

    Returns:
        - HttpResponseRedirect redirecting the user to WIMS, logged in his WIMS' class.
        - HttpResponse(status=502) if an error occured while communicating with the WIMS server.
        - HttpResponse(status=504) if the WIMS server could not be joined."""
    if request.method == "GET":
        uri = request.build_absolute_uri()
        return HttpResponseNotAllowed(["POST"], GET_ERROR_MSG % (uri[:-1], uri))
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"], "405 Method Not Allowed: '%s'" % request.method)
    
    try:
        parameters = parse_parameters(request.POST)
        logger.info("Request received from '%s'" % request.META.get('HTTP_REFERER', "Unknown"))
        check_parameters(parameters)
        is_valid_request(request)
    except BadRequestException as e:
        logger.info(str(e))
        return HttpResponseBadRequest(str(e))
    
    # Retrieve the WIMS server
    try:
        wims_srv = WIMS.objects.get(pk=wims_pk)
    except WIMS.DoesNotExist:
        raise Http404("Unknown WIMS server of id '%d'" % wims_pk)
    
    # Retrieve the LMS
    try:
        lms = LMS.objects.get(guid=parameters["tool_consumer_instance_guid"])
    except LMS.DoesNotExist:
        raise Http404("No LMS found with guid '%s'" % parameters["tool_consumer_instance_guid"])
    
    wapi = wimsapi.WimsAPI(wims_srv.url, wims_srv.ident, wims_srv.passwd)
    
    try:
        # Check that the WIMS server is available
        bol, response = wapi.checkident(verbose=True)
        if not bol:
            raise wimsapi.WimsAPIError(response['message'])
        
        # Check whether the class already exists, creating it otherwise
        wclass_db, wclass = get_or_create_class(lms, wims_srv, wapi, parameters)
        
        # Check whether the user already exists, creating it otherwise
        user_db, user = get_or_create_user(wclass_db, wclass, parameters)
        
        # Trying to authenticate the user on the WIMS server
        bol, response = wapi.authuser(wclass.qclass, wclass.rclass, user.quser)
        if not bol:  # pragma: no cover
            raise wimsapi.WimsAPIError(response['message'])
        url = response["home_url"] + ("&lang=%s" % wclass.lang)
    
    except wimsapi.WimsAPIError as e:  # WIMS server responded with ERROR
        logger.info(str(e))
        return HttpResponse(str(e), status=502)
    
    except requests.RequestException:
        logger.exception("Could not join the WIMS server '%s'" % wims_srv.url)
        return HttpResponse("Could not join the WIMS server '%s'" % wims_srv.url, status=504)
    
    return redirect(url)



def wims_sheet(request: HttpRequest, wims_pk: int, sheet_pk: int) -> HttpResponse:
    """Redirect the client to the WIMS server corresponding to <wims_pk> and sheet <sheet_pk>.

        Will retrieve/create the right WIMS' class/user according to informations in request.POST.

        Raises:
            - Http404 if no LMS corresponding to request.POST["tool_consumer_instance_guid"]
                has been found in the database.
            - PermissionDenied if the class corresponding to request.POST['context_id'] does not
                exists and roles in request.POST['context_id'] are not one of
                settings.ROLES_ALLOWED_CREATE_WIMS_CLASS.

        Returns:
            - HttpResponseRedirect redirecting the user to WIMS, logged in his WIMS' class.
            - HttpResponse(status=502) if an error occured while communicating with the WIMS.
            - HttpResponse(status=504) if the WIMS server could not be joined."""
    if request.method == "GET":
        uri = request.build_absolute_uri()
        return HttpResponseNotAllowed(["POST"], GET_ERROR_MSG % (uri[:-1], uri))
    if request.method != "POST":
        return HttpResponseNotAllowed(["POST"], "405 Method Not Allowed: '%s'" % request.method)
    
    try:
        parameters = parse_parameters(request.POST)
        logger.info("Request received from '%s'" % request.META.get('HTTP_REFERER', "Unknown"))
        check_parameters(parameters)
        is_valid_request(request)
    except BadRequestException as e:
        logger.info(str(e))
        return HttpResponseBadRequest(str(e))
    
    # Retrieve the WIMS server
    try:
        wims_srv = WIMS.objects.get(pk=wims_pk)
    except WIMS.DoesNotExist:
        raise Http404("Unknown WIMS server of id '%d'" % wims_pk)
    
    # Retrieve the LMS
    try:
        lms = LMS.objects.get(guid=parameters["tool_consumer_instance_guid"])
    except LMS.DoesNotExist:
        raise Http404("No LMS found with guid '%s'" % parameters["tool_consumer_instance_guid"])
    
    wapi = wimsapi.WimsAPI(wims_srv.url, wims_srv.ident, wims_srv.passwd)
    
    try:
        # Check that the WIMS server is available
        bol, response = wapi.checkident(verbose=True)
        if not bol:
            raise wimsapi.WimsAPIError(response['message'])
        
        # Get the class
        wclass_db = WimsClass.objects.get(wims=wims_srv, lms=lms,
                                          lms_guid=parameters['context_id'])
        
        try:
            wclass = wimsapi.Class.get(
                wims_srv.url, wims_srv.ident, wims_srv.passwd, wclass_db.qclass, wims_srv.rclass,
                timeout=settings.WIMSAPI_TIMEOUT
            )
        except wimsapi.WimsAPIError as e:
            if "not existing" in str(e):  # Class was deleted on the WIMS server
                qclass = wclass_db.qclass
                logger.info(("Deleting class (id : %d - wims id : %s - lms id : %s) as it was"
                             "deleted from the WIMS server")
                            % (wclass_db.id, str(wclass_db.qclass), str(wclass_db.lms_guid)))
                wclass_db.delete()
                return HttpResponseNotFound(
                    ("Class of ID %s could not be found on the WIMS server. Maybe it has been "
                     "deleted from the WIMS server. Use this LTI link on your LMS to create a new "
                     "WIMS class: %s")
                    % (qclass,
                       request.build_absolute_uri(reverse("lti:wims_class", args=[wims_pk])))
                )
            raise  # Unknown error (pragma: no cover)
        
        # Check whether the user already exists, creating it otherwise
        user_db, user = get_or_create_user(wclass_db, wclass, parameters)
        
        # Check whether the sheet already exists, creating it otherwise
        sheet_db, sheet = get_sheet(wclass_db, wclass, sheet_pk, parameters)
        if int(sheet.sheetmode) not in [1, 2]:  # not active or expired
            return HttpResponseForbidden("This WIMS sheet (%s) is currently unavailable (%s)"
                                         % (str(sheet.qsheet), MODE[int(sheet.sheetmode)]))
        
        # Storing the URL and ID to send the grade back to the LMS
        try:
            gl = GradeLinkSheet.objects.get(user=user_db, activity=sheet_db)
            gl.sourcedid = parameters["lis_result_sourcedid"]
            gl.url = parameters["lis_outcome_service_url"]
            gl.save()
        except GradeLinkSheet.DoesNotExist:
            GradeLinkSheet.objects.create(user=user_db, activity=sheet_db, lms=lms,
                                          sourcedid=parameters["lis_result_sourcedid"],
                                          url=parameters["lis_outcome_service_url"])
        
        # If user is a teacher, send all grade back to the LMS
        role = Role.parse_role_lti(parameters["roles"])
        if is_teacher(role):
            GradeLinkSheet.send_back_all(sheet_db)
        
        # Trying to authenticate the user on the WIMS server
        bol, response = wapi.authuser(wclass.qclass, wclass.rclass, user.quser)
        if not bol:  # pragma: no cover
            raise wimsapi.WimsAPIError(response['message'])
        
        params = "&lang=%s&module=adm%%2Fsheet&sh=%s" % (wclass.lang, str(sheet.qsheet))
        url = response["home_url"] + params
    
    except WimsClass.DoesNotExist as e:
        logger.info(str(e))

lti_app/templates/lti_app/activities.html
{% extends 'lti_app/base.html' %}

{% load static %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-1">
            <li class="breadcrumb-item">
                <a href="{% url 'lti:lms' %}"><i class="fas fa-home"></i></a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'lti:wims' LMS.pk %}">{{ LMS.name }}</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'lti:classes' LMS.pk WIMS.pk %}">{{ WIMS.name }}</a>
            </li>
            <li class="breadcrumb-item active">{{ class.name }}</li>
        </ol>
    </nav>
    {%  if sheets or exams %}
        <div id="filter-container" class="md-form active-cyan-2 mb-3">
            <input id="filter" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>
    {% endif %}
    {% if sheets %}
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Sheet</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">LTI-URL</th>
                </tr>
            </thead>
            <tbody>
                {% for item in sheets %}
                    <tr>
                        <td>{{ item.qsheet }}</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.sheetmode }}</td>
                        <td>
                            <code>{{ item.lti_url }}</code>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            No worksheet has been found on this class.
        </div>
    {% endif %}

    <br>

    {% if exams %}
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Exam</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">LTI-URL</th>
                </tr>
            </thead>
            <tbody>
                {% for item in exams %}
                    <tr>
                        <td>{{ item.qexam }}</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.exammode }}</td>
                        <td>
                            <code>{{ item.lti_url }}</code>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            No exam has been found on this class.
        </div>
    {% endif %}
{% endblock %}

lti_app/templates/lti_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>WIMS - LTI</title>
        
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
              integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/lti_app.css' %}"/>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
    </head>

    <body onload="pageLoaded()">
        <div class="container table-hover">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>

        <script>
            $('tr[data-href]').on("click", function () {
                document.location = $(this).data('href');
            });

            $('td[data-href]').on("click", function () {
                document.location = $(this).data('href');
            });
        </script>

        <script type="text/javascript">
            function pageLoaded() {
                let filterInput = document.getElementById('filter');
                // Set the cursor into the filter-<input>
                filterInput.focus();
                filterInput.select();
                // Call filtering method on every keyup
                filterInput.onkeyup = function () {
                    filterTable(filterInput.value);
                };


                // Filter the table for a given search-string
                function filterTable(value) {
                    let rows = document.getElementsByTagName('tr');
                    let rowsLength = rows.length;

                    for (let i = 0; i < rowsLength; ++i) {
                        if (value === '') {
                            rows[i].className = 'show';
                        } else {
                            let tds = rows[i].getElementsByTagName('td');
                            let tdsLength = tds.length;

                            rows[i].className = 'hide';

                            for (let tdsCounter = 0; tdsCounter < tdsLength; ++tdsCounter) {
                                if (tds[tdsCounter].innerText.indexOf(value) > -1) {
                                    tds[tdsCounter].parentNode.className = 'show';
                                    continue;
                                }
                            }
                        }
                    }
                }
            }
        </script>
        {% block end_script %}{% endblock %}
    </body>
</html>

lti_app/templates/lti_app/classes.html
{% extends 'lti_app/base.html' %}

{% load static %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-1">
            <li class="breadcrumb-item"><a href="{% url 'lti:lms' %}">
                <i class="fas fa-home"></i>
            </a></li>
            <li class="breadcrumb-item"><a href="{% url 'lti:wims' LMS.pk %}">{{ LMS.name }}</a>
            </li>
            <li class="breadcrumb-item active">{{ WIMS.name }}</li>
        </ol>
    </nav>
    
    <table class="table table-striped">
        <tbody>
            <tr>
                <td data-href="{% url 'lti:classes' LMS.pk WIMS.pk %}">{{ WIMS.name }}</td>
                <td><code>{{ WIMS.url }}</code></td>
                <td>
                    <code>{{ request.scheme }}://{{ request.get_host }}{% url 'lti:wims_class' WIMS.pk %}</code>
                </td>
            </tr>
        </tbody>
    </table>

    {% if classes %}
        <div id="filter-container" class="md-form active-cyan-2 mb-3">
            <input id="filter" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"><i class="fas fa-graduation-cap"></i></th>
                    <th scope="col">Classe</th>
                    <th scope="col">Name</th>
                    <th scope="col">ID LMS</th>
                    <th scope="col">ID WIMS</th>
                </tr>
            </thead>
            <tbody>
                {% for item in classes %}
                    <tr data-href="{% url 'lti:sheets' LMS.pk WIMS.pk item.pk %}">
                        <td><i class="fas fa-caret-down"></i></td>
                        <td>{{ item.pk }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.lms_guid }}</td>
                        <td>{{ item.qclass }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            No class has been created through LTI on this WIMS server.
        </div>
    {% endif %}
{% endblock %}

lti_app/templates/lti_app/lms.html
{% extends 'lti_app/base.html' %}

{% load static %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-1">
            <li class="breadcrumb-item active"><i class="fas fa-home"></i></li>
        </ol>
    </nav>
    {% if LMS %}
        <div id="filter-container" class="md-form active-cyan-2 mb-3">
            <input id="filter" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"><i class="fas fa-graduation-cap"></i></th>
                    <th scope="col">LMS</th>
                    <th scope="col">Name</th>
                    <th scope="col">URL</th>
                </tr>
            </thead>
            <tbody>
                {% for item in LMS %}
                    <tr>
                        <td data-href="{% url 'lti:wims' item.pk %}"><i class="fas fa-caret-down"></i></td>
                        <td data-href="{% url 'lti:wims' item.pk %}">{{ item.pk }}</td>
                        <td data-href="{% url 'lti:wims' item.pk %}">{{ item.name }}</td>
                        <td><code>{{ item.url }}</code></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            No LMS has been added to this server.
        </div>
    {% endif %}
{% endblock %}

lti_app/templates/lti_app/wims.html
{% extends 'lti_app/base.html' %}

{% load static %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb p-1">
            <li class="breadcrumb-item"><a href="{% url 'lti:lms' %}">
                <i class="fas fa-home"></i>
            </a></li>
            <li class="breadcrumb-item active">{{ LMS.name }}</li>
        </ol>
    </nav>
    {% if WIMS %}
        <div id="filter-container" class="md-form active-cyan-2 mb-3">
            <input id="filter" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"><i class="fas fa-graduation-cap"></i></th>
                    <th scope="col">WIMS</th>
                    <th scope="col">Name</th>
                    <th scope="col">URL</th>
                    <th scope="col">LTI-URL</th>
                </tr>
            </thead>
            <tbody>
                {% for item in WIMS %}
                    <tr>
                        <td data-href="{% url 'lti:classes' LMS.pk item.pk %}"><i class="fas fa-caret-down"></i></td>
                        <td data-href="{% url 'lti:classes' LMS.pk item.pk %}">{{ item.pk }}</td>
                        <td data-href="{% url 'lti:classes' LMS.pk item.pk %}">{{ item.name }}</td>
                        <td><code>{{ item.url }}</code></td>
                        <td>
                            <code>{{ request.scheme }}://{{ request.get_host }}{% url 'lti:wims_class' item.pk %}</code>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            No WIMS server has allowed this LMS.
        </div>
    {% endif %}
{% endblock %}